### ISSUE TITLE
Adding a button to settings.

### ISSUE THREAD

**Issue by prestig9110** [CyaNox/Noxys_Waterfill#4]
I played with this mod for a very long time and sometimes the ore removal function came in handy for me, now it has been removed. For example, you can add some setting so that you can do it as before, but by default, what would it be turned off? 

Conditionally as on the screen.
![image](https://user-images.githubusercontent.com/69300202/160468536-b3ee9ced-81ac-4363-a4b1-15c2b8f7baa1.png)

I would be very grateful. Without this setup, I will not be able to implement a project that took 200 hours to prepare. And only now I learned about the ban on the remove of ore

**Comment by NoxyNixie** [comment]
![image](https://user-images.githubusercontent.com/211381/160476958-e5f77083-49c8-4aac-b666-4bae55ae44f6.png)

I believe this setting does exactly what you want and more.

**Comment by prestig9110** [comment]
Many thanks.
